version: "3.9"

services:
  huawei-backup:
    build: .
    container_name: huawei-backup
    restart: always
    env_file:
      - .env
    volumes:
      - /opt/huawei-backup/backups:/backups
      - /opt/huawei-backup/logs:/logs
    tty: true
